// data.js
export const DATA_VERSION = "1.0.1"; // ← Change this number
export const INITIAL_CATEGORIES = [
  { id: "cat-1", name: "Ai Photo Editing", slug: "ai-photo-editing" },
  { id: "cat-2", name: "Ai Video Editing Free", slug: "ai-video-editing-free" },
  { id: "cat-3", name: "Capcut Template", slug: "capcut-template" },
  { id: "cat-4", name: "VN Code Template", slug: "vn-code-template" },
  {
    id: "cat-5",
    name: "Lightroom Photo Edit Preset",
    slug: "lightroom-photo-edit-preset",
  },
];

export const INITIAL_PAGES = [
  {
    id: "about-us",
    title: "About Us",
    content: `Welcome to AI with Vishu

Hello! AI with Vishu is a professional platform where we provide interesting and valuable content focused on Photo & Video Editing.

We are committed to delivering high-quality, reliable, and insightful information. Our goal is to turn our passion for Photo & Video Editing into a thriving online resource.

We will continue to post such valuable and knowledgeable information on our website for all of you. Your love and support mean a lot to us.

We are dedicated to providing you with the very best insights and knowledge related to Photo & Video Editing.

We hope you find all of the information on AI with Vishu helpful, as we love sharing it with you.

### Our Mission

Our mission is to empower creators, editors, and content creators with the tools and knowledge they need to create stunning visual content. We believe that everyone has the potential to become a great editor, and we are here to guide you every step of the way.

### Why Choose AI with Vishu?

- **Expert Guidance**: Learn from experienced professionals who have been in the industry for years.
- **Free Resources**: Access high-quality tutorials, prompts, and presets without any cost.
- **Community Support**: Join a growing community of like-minded creators who share tips and feedback.
- **Regular Updates**: Stay ahead of the curve with the latest trends and techniques in photo and video editing.

### What We Offer

At AI with Vishu, we provide a wide range of resources including:
- **AI Photo Editing Tutorials**: Learn how to create stunning images using AI tools like Midjourney, DALL-E, and Bing Image Creator.
- **AI Video Editing Tutorials**: Master the art of creating viral videos using tools like RunwayML, CapCut, and VN Video Editor.
- **CapCut Templates**: Get access to ready-to-use templates that will make your Reels and Shorts go viral.
- **Lightroom Presets**: Download premium presets to give your photos a professional look with just one click.

### Our Vision

We envision a world where anyone can create professional-quality content without spending thousands of dollars on expensive software or courses. AI with Vishu is your one-stop destination for all things editing.

### Join Our Community

Connect with us on social media to stay updated with the latest tutorials and trends:
- **Instagram**: @the_vishesh_001
- **Telegram**: @visheshpal001
- **YouTube**: @CricNews-v2l

Together, we can create amazing content that inspires and entertains millions of people around the world.

Thank you for being a part of AI with Vishu!`,
    email: "palvishesh613@gmail.com",
  },
  {
    id: "privacy-policy",
    title: "Privacy Policy",
    lastUpdated: "July 24, 2026",
    content: `This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.

We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.

### Interpretation and Definitions

#### Definitions

For the purposes of this Privacy Policy:

- **Account** means a unique account created for You to access our Service or parts of our Service.
- **Company** (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to AI with Vishu.
- **Cookies** are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
- **Country** refers to: India
- **Device** means any device that can access the Service such as a computer, a cellphone or a digital tablet.
- **Personal Data** is any information that relates to an identified or identifiable individual.
- **Service** refers to the Website.
- **Service Provider** means any natural or legal person who processes the data on behalf of the Company.
- **Usage Data** refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.
- **Website** refers to AI with Vishu, accessible from this applet.
- **You** means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.

### Collecting and Using Your Personal Data

#### Types of Data Collected

##### Personal Data

While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:

- Email address
- First name and last name
- Usage Data

##### Usage Data

Usage Data is collected automatically when using the Service.

Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.

When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.

### Tracking Technologies and Cookies

We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.

You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.

### Use of Your Personal Data

The Company may use Personal Data for the following purposes:

- **To provide and maintain our Service**, including to monitor the usage of our Service.
- **To manage Your Account**: to manage Your registration as a user of the Service.
- **To contact You**: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.
- **To provide You** with news, special offers and general information about other goods, services and events.
- **To manage Your requests**: To attend and manage Your requests to Us.

### Retention of Your Personal Data

The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.

### Security of Your Personal Data

The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.

### Children's Privacy

Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.

### Links to Other Websites

Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.

### Changes to this Privacy Policy

We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.

We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.

### Contact Us

If you have any questions about this Privacy Policy, You can contact us:

- By email: palvishesh613@gmail.com`,
  },
  {
    id: "terms-and-condition",
    title: "Terms and condition",
    lastUpdated: "July 24, 2026",
    content: `Welcome to AI with Vishu! These terms and conditions outline the rules and regulations for the use of our Website.

By accessing this website, we assume you accept these terms and conditions in full. Do not continue to use AI with Vishu's website if you do not accept all of the terms and conditions stated on this page.

The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: "Client", "You" and "Your" refers to you, the person log on this website and compliant to the Company's terms and conditions. "The Company", "Ourselves", "We", "Our" and "Us", refers to our Company. "Party", "Parties", or "Us", refers to both the Client and ourselves.

### Intellectual Property Rights

Other than content you own, under these Terms, AI with Vishu and/or its licensors own all the intellectual property rights and materials contained in this Website.

You are granted a limited license only for purposes of viewing the material contained on this Website.

### Restrictions

You are specifically restricted from all of the following:

- Publishing any Website material in any other media without credit.
- Selling, sublicensing and/or otherwise commercializing any Website material.
- Publicly performing and/or showing any Website material.
- Using this Website in any way that is or may be damaging to this Website.
- Using this Website in any way that impacts user access to this Website.
- Using this Website contrary to applicable laws and regulations, or in any way may cause harm to the Website, or to any person or business entity.
- Engaging in any data mining, data harvesting, data extracting or any other similar activity in relation to this Website.
- Using this Website to engage in any advertising or marketing.

### Your Content

In these Terms and Conditions, "Your Content" shall mean any audio, video, text, images or other material you choose to display on this Website. By displaying Your Content, you grant AI with Vishu a non-exclusive, worldwide, irrevocable, royalty-free, sublicensable license to use, reproduce, adapt, publish, translate and distribute it in any and all media.

### No Warranties

This Website is provided "as is," with all faults, and AI with Vishu makes no express or implied representations or warranties, of any kind related to this Website or the materials contained on this Website. Additionally, nothing contained on this Website shall be construed as providing consult or advice to you.

### Limitation of Liability

In no event shall AI with Vishu, nor any of its officers, directors and employees, be held liable for anything arising out of or in any way connected with your use of this Website whether such liability is under contract. AI with Vishu, including its officers, directors and employees shall not be held liable for any indirect, consequential or special liability arising out of or in any way related to your use of this Website.

### Indemnification

You hereby indemnify to the fullest extent AI with Vishu from and against any and/or all liabilities, costs, demands, causes of action, damages and expenses arising in any way related to your breach of any of the provisions of these Terms.

### Severability

If any provision of these Terms is found to be invalid under any applicable law, such provisions shall be deleted without affecting the remaining provisions herein.

### Variation of Terms

AI with Vishu is permitted to revise these Terms at any time as it sees fit, and by using this Website you are expected to review these Terms on a regular basis.

### Assignment

AI with Vishu is allowed to assign, transfer, and subcontract its rights and/or obligations under these Terms without any notification. However, you are not allowed to assign, transfer, or subcontract any of your rights and/or obligations under these Terms.

### Entire Agreement

These Terms constitute the entire agreement between AI with Vishu and you in relation to your use of this Website, and supersede all prior agreements and understandings.

### Governing Law & Jurisdiction

These Terms will be governed by and interpreted in accordance with the laws of India, and you submit to the non-exclusive jurisdiction of the state and federal courts located in India for the resolution of any disputes.`,
  },
  {
    id: "disclaimer",
    title: "Disclaimer",
    lastUpdated: "July 24, 2026",
    content: `The information contained on the Service is for general information purposes only.

The Company assumes no responsibility for errors or omissions in the contents of the Service.

In no event shall the Company be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service.

The Company reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.

The Company does not warrant that the Service is free of viruses or other harmful components.

### External Links Disclaimer

The Service may contain links to external websites that are not provided or maintained by or in any way affiliated with the Company.

Please note that the Company does not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites.

### Affiliate Disclaimer

This Service may contain links to affiliate websites, and we receive an affiliate commission for any purchases made by you on the affiliate website using such links.

Our affiliates include:
- Google (Bard, Gemini, Images)
- Microsoft (Bing, DALL-E)
- RunwayML
- CapCut
- VN Video Editor

### Accuracy of Information Disclaimer

The information provided on this Service is for general informational purposes only and should not be considered as professional advice.

While we strive to keep the information up to date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability with respect to the Service or the information, products, services, or related graphics contained on the Service for any purpose.

Any reliance you place on such information is therefore strictly at your own risk.

### Professional Advice Disclaimer

The information provided on this Service is not intended to be a substitute for professional advice. Before making any decisions, you should consult with appropriate professionals.

### User Responsibility

It is your responsibility to ensure that any products, services, or information available through this Service meet your specific requirements.

You acknowledge that the use of any information or materials on this Service is entirely at your own risk, for which we shall not be liable.

### Copyright Disclaimer

All content on this Service, including text, graphics, logos, images, and software, is the property of AI with Vishu and is protected by copyright laws.

You may not reproduce, distribute, or create derivative works from any content on this Service without our express written permission.

### Fair Use Disclaimer

Some content on this Service may contain copyrighted material that has not been specifically authorized by the copyright owner. We believe this constitutes "fair use" as provided for in section 107 of the US Copyright Law.

If you wish to use copyrighted material from this Service for purposes that go beyond fair use, you must obtain permission from the copyright owner.

### Contact Information

If you have any questions about this Disclaimer, please contact us:

- By email: palvishesh613@gmail.com
- By phone: 9628810149

### Updates to This Disclaimer

We reserve the right to update this Disclaimer at any time. We will notify you of any changes by posting the new Disclaimer on this page.

This Disclaimer was last updated on July 24, 2026.`,
  },
  {
    id: "contact-us",
    title: "Contact us",
    content: `Welcome to AI with Vishu. We're always eager to hear from you. Whether you want to share feedback, ask questions, or simply say hello, we're here and ready to listen. At AI with Vishu your thoughts and suggestions help us grow, improve, and deliver a better experience.

### How Can We Help You?

You can contact us for any of the following reasons:

- **Website Feedback**: If you have any thoughts, opinions, or comments about our website, its design, or functionality.
- **Content Queries**: Have a question or concern about our content or tutorials.
- **Corrections or Updates**: If you come across any information in our posts that seems incorrect or outdated.
- **Design & Feature Suggestions**: Do you have ideas on how we can improve our website's appearance or usability?
- **Business Inquiries**: For partnerships, collaborations, or sponsorship opportunities.
- **Technical Support**: If you're experiencing any issues with our website or tutorials.
- **General Questions**: Any other questions you might have about AI with Vishu.

### How to Reach Us

We welcome all your comments, suggestions, and concerns! Here's how you can get in touch with us:

#### Email
For general inquiries, feedback, or support:
📧 **palvishesh613@gmail.com**

We strive to respond to all emails within 24-48 hours.

#### Phone
For urgent matters or if you prefer to speak directly:
📞 **9628810149**

Our phone lines are open Monday to Friday, 10:00 AM to 6:00 PM IST.

### Connect With Us on Social Media

Stay connected and follow us for daily updates, tips, and tutorials:

- **Instagram**: @the_vishesh_001
- **Telegram**: @visheshpal001
- **YouTube**: @CricNews-v2l
- **WhatsApp**: Available for quick queries

### Frequently Asked Questions

**Q: How quickly can I expect a response?**
A: We aim to respond to all queries within 24-48 hours.

**Q: Do you offer one-on-one consultation?**
A: Yes! We offer personalized consultation sessions for advanced editing techniques. Contact us for more details.

**Q: Can I suggest a tutorial topic?**
A: Absolutely! We love hearing your ideas. If there's a specific topic you'd like us to cover, please let us know.

**Q: Are your tutorials really free?**
A: Yes! All our tutorials, prompts, and resources are completely free. We believe in making high-quality editing knowledge accessible to everyone.

**Q: Do you collaborate with other creators?**
A: Yes, we're always open to collaborations. If you're interested in working together, please reach out to us via email.

### Location

Based in India, we serve creators and editors from all around the world. Our content is designed to be accessible and helpful regardless of your location.

### Office Hours

- Monday to Friday: 10:00 AM - 6:00 PM IST
- Saturday: 12:00 PM - 4:00 PM IST
- Sunday: Closed

### Response Time

We value your time and aim to respond to all inquiries as quickly as possible. Our typical response times are:

- **Email**: Within 24-48 hours
- **Social Media**: Within 12-24 hours
- **Phone**: Immediate during business hours

### Let's Build Something Amazing Together

Your feedback, ideas, and suggestions help us create better content and resources for you. Whether you're a beginner just starting your editing journey or an experienced creator looking to level up, we're here to support you every step of the way.

Thank you for being a part of the AI with Vishu community. We look forward to hearing from you!

**Connect with us today and let's create something extraordinary together!**`,
    email: "palvishesh613@gmail.com",
    phone: "9628810149",
  },
];

export const INITIAL_POSTS = [
  {
    id: "post-1",
    title: "Motu Patlu City Explore AI Video Editing Tutorial | Step-by-Step",
    categoryId: "cat-2", // Ai Video Editing Free
    image: "/images/post1/motu1.png",
    date: "July 7, 2026",
    author: "Vishu",
    introduction: `Friends, you all use social media and every day some trend or the other keeps going on on social media. Currently, videos of Motu Patlu exploring the city made with AI are going viral all over social media, in which they explore the city and give reviews of that city. Whoever is getting this video is also making his own video with the help of City AI and uploading it on his social media, which is getting him lakhs of views. Because these videos are so engaging to watch that they attract everyone's attention. Motu Patlu is already such a viral cartoon and when these silly exploration videos are shown, people are surprised.

Friends, if you also want to make a similar silly exploration video of your own and want to grow on social media by uploading it, then this is the best time to make this video. In this article, I will tell you everything about how you want to make this Motu Patlu mall explore video. So read this article today very carefully so that you do not miss any information.`,
    whyTrending: `Motu Patlu City Explore video is so viral because these characters are in cartoon style and moreover it is about silly exploration which is liked the most by the people living in that city. You all know how much everyone from children to young people likes cartoons in which Motu Patlu goes exploring the city and they enjoy watching them with great pleasure.

Another reason is that creators, big and small, are making such videos to upload them on their social media platforms to get views, due to which it is becoming more and more popular. These videos also perform well because they are short, colorful, and entertaining. The simple storytelling and eye-catching visuals encourage viewers to watch until the end and share the videos with others.`,
    creationIntro: `Making a Motu Patlu city explore ai video is very easy, you will be able to make it within just 2-4 minutes. The process of making this video is divided into 2 parts. First of all, you have to generate the image of Motu Patlu and then you have to convert that image into video with the help of AI. I am telling you step by step how to do all this so that you do not get confused.`,

    // Photo step
    photoStepTitle: "Steps to Create Photo :",
    photoStepImage: "/images/post1/motu2.jpg",
    photoPrompt:
      "IMAGE PROMPT:- es photo me jo Azamgarh likha hai usko hata ke (Apni City ka name likho ) likh do baki sab same rhega …",
    photoBtnText: "Create Your Image",
    photoBtnLink: "https://chat.openai.com/",

    // Video step
    videoStepTitle: "Steps to Make Video :",
    videoStepImage: "/images/post1/motu3.jpg",
    videoPrompt:
      "VIDEO PROMPT :- हेलो दोस्तो हम लोग जौनपुर आ गए हैं यहां का नजारा काफी अच्छा है क्या आप कभी इधर आए हैं",
    videoBtnText: "Create Your Video",
    videoBtnLink: "https://flow.google/",

    faqs: [
      {
        id: "faq-1",
        question: "What is a Motu Patlu City Explore AI video?",
        answer:
          "A Motu Patlu City Explore AI video is a short animated video where Motu and Patlu-style characters appear in different cities. These videos are created using AI image generation and AI video tools, then edited for social media platforms like Instagram Reels and YouTube Shorts.",
      },
      {
        id: "faq-2",
        question: "Do I need any editing experience?",
        answer:
          "No. Most AI tools are beginner-friendly. If you can follow simple steps and use a basic video editor, you can create these videos without any professional experience.",
      },
      {
        id: "faq-3",
        question: "Which AI tools can I use to create the image?",
        answer:
          "You can use Google Gemini, Bing Image Creator (DALL-E 3), or Midjourney to generate high-quality cartoon images. These will give you great results, making your video more professional.",
      },
      {
        id: "faq-4",
        question: "How can I change the city name?",
        answer:
          "To write the name of your city, you have to go to the image prompt and put the name of your city in the quotes, and the photo will be created with the name of your city.",
      },
      {
        id: "faq-5",
        question: "Can I use these videos on YouTube or Instagram?",
        answer:
          "Yes, you can upload AI-generated videos to social media. However, make sure your content follows the platform's rules and respects the intellectual property rights of any recognizable characters or brands you depict.",
      },
    ],
    conclusion: `Creating a Motu Patlu style City Explore AI video is easier than many people think. With the right AI image prompt, a good video tool, and a few simple editing steps, you can create videos that look attractive and fun to watch. You don't need expensive software or professional editing skills to get started. Try different city names, backgrounds, and camera angles to make every video unique. Keep your editing clean and use smooth animations for the best results. The more you practice, the better your videos will become.

We hope this guide helped you understand the complete process from creating the image to making the final AI video. Now it's your turn to try these steps and create your own City Explore videos. Keep learning, keep creating, and enjoy making amazing AI content.`,
    tags: [
      "AI Animation",
      "AI Video",
      "How To Create AI Video",
      "Motu Patlu",
      "Motu Patlu Photo",
      "Motu Patlu City Explore",
    ],
    isTrending: true,
    comments: [
      {
        id: "c-1",
        author: "Rohan Sharma",
        email: "rohan@gmail.com",
        content:
          "Wow! This is a very helpful tutorial. I made a video of my city Jaunpur and it got 50k views on Reels!",
        date: "July 10, 2026",
      },
    ],
  },
  {
    id: "post-2",
    title: "Create Your Emotional AI Photo With Your Face",
    categoryId: "cat-1", // Ai Photo Editing
    image: "/images/post2/edit1.png",
    date: "July 18, 2026",
    author: "Vishu ",
    introduction: `Have you ever stopped scrolling because a single photo caught your attention? Maybe it was someone sitting quietly beside a rainy window, walking alone on an empty road, or looking at the sky with a broken heart. These photos feel different because they don't just show a person—they tell a story. This is exactly why emotional AI photos have become one of the biggest trends on Instagram, WhatsApp, Facebook, and Pinterest. They look like scenes from a movie, but most of them are created with AI in just a few minutes.

The best part is that you don't need to be a professional photo editor. You don't need Photoshop or expensive software either. If you have a clear photo of yourself and a good AI prompt, you can create amazing emotional portraits that look realistic and natural.

In this guide, I'll explain everything in simple English. Whether you're a beginner or someone who has never used AI before, you can easily follow these steps and create your own cinematic AI photo.`,
    whyTrending: `People love photos that make them feel something. A normal selfie might get a few likes, but a photo that tells a story often gets much more attention. Imagine two different pictures. One is a simple selfie. The other shows the same person sitting alone in the rain with soft street lights, a cloudy sky, and a thoughtful expression. Which one would you stop to look at? Most people choose the second one because it creates emotion.

That is the reason these AI photos are becoming viral. They look realistic, they tell a story, and they connect with people without using many words. Many creators also use these images for Instagram posts, WhatsApp Status, YouTube thumbnails, Facebook covers, and Pinterest pins because they stand out from regular photos.`,
    creationIntro: `How do you make such an emotional photo and which tool is required for it, I am telling you the entire process step by step and in detail. By reading and following these steps, you can easily create your own photo.

First of all you have to download Chatgpt app from Google Play Store if you do not have it.
After downloading, you have to login with your Gmail.
Now you have to come back to the website and copy the prompt given below the photo from this post.
Scroll down a bit and click on the create your image button.
Now you have to select a photo of yourself by clicking on the plus icon of the chat. 
Then paste the copied prompt and click on the send button.
Now Chatgpt will start creating your photo and your photo will be ready in a short while.`,

    // 🔥 Multiple Images + Prompts
    photoStepTitle: "Steps to Generate Emotional Photos:",
    photoItems: [
      {
        image: "/images/post2/edit2.webp",
        prompt: `"Moody low-light pics of a young person from reference image, tired expression, emo/alt aesthetic. Generate Four-images, n=4, images ratio 9:16
1. lying on a pillow, face partially hidden, dim blue lighting, soft shadows
2. sitting in darkness, hand covering mouth, contemplative mood, grainy texture
3. extreme close-up of face resting sideways, blurry, dreamy, cinematic noise
4. mirror selfie, black oversized outfit with graphic tee, one hand in hair, dim room lighting Overall dark, desaturated tones, soft blur, film grain, melancholic atmosphere, night-time bedroom setting, indie aesthetic, slightly hazy focus."`,
        title: "Moody Night Photos",
      },
      {
        image: "/images/post2/edit3.webp",
        prompt: `Create an ultra-realistic cinematic heartbreak portrait using the uploaded person's photo as the exact face and identity reference. Keep the person's face, hairstyle, beard, eyebrows, eyes, nose, lips, jawline, skin tone, body shape, pose, clothes, watch, and overall identity 100% identical to the uploaded photo. Do not change the person's facial features or identity. Transform the scene into a rainy night in an empty city park. The person is sitting alone on a wet wooden bench with his head lowered, looking emotionally broken and lost in deep thoughts. He is silently holding a torn handwritten love letter with both hands. A single fresh red rose lies beside him on the bench, with a few fallen petals scattered on the wet wood. The park is empty with old street lamps casting warm golden light. Heavy rain is falling, the ground is wet with realistic reflections, soft fog fills the background, and distant city lights create beautiful cinematic bokeh. Add realistic raindrops on the clothes, hair, hands, and bench. The overall mood should feel lonely, emotional, and heartbreaking, like a dramatic movie scene after a painful goodbye. Add a subtle handwritten quote in the top-right corner:

"Some hearts never heal, they just learn to survive."

Use dramatic cinematic lighting, volumetric fog, HDR, 85mm lens, f/1.4 aperture, shallow depth of field, ultra-realistic skin texture, natural color grading, realistic rain physics, soft shadows, professional Photoshop composite, 8K quality, emotional storytelling, award-winning cinematic photography.

Negative Prompt: cartoon, anime, painting, CGI, 3D render, illustration, low quality, blurry, extra people, duplicate face, wrong face, different hairstyle, smiling, daylight, oversaturated colors, watermark, logo, text artifacts, bad anatomy, unrealistic hands, deformed fingers, low resolution.`,
        title: "Heartbreak Rain Scene",
      },
      {
        image: "/images/post2/edit4.webp",
        prompt: `Create an ultra-realistic dark emotional cinematic portrait using the uploaded person's photo as the exact face and identity reference. Keep the face, hairstyle, eyebrows, eyes, nose, lips, beard, jawline, skin tone, body shape, pose, and facial proportions 100% identical to the uploaded photo. Do not change the person's identity. The person is wearing a black hoodie and sitting alone at night with a sad, heartbroken expression, looking slightly downward. The background is dark, moody, and cinematic with soft rain, cold blue tones, blurred city lights, and dramatic lighting. Behind the person, create a realistic emotional memories collage including:

• A lonely man walking on an empty road at night.
• A silhouette of a couple standing together.
• A broken heart photo pinned with tape.
• A lonely person sitting on a park bench.
• Handwritten emotional quotes blended naturally into the background.

Text on image:
"The worst kind of pain is when you're smiling just to stop the tears from falling."
"Memories never die, they just hurt more."
"Some people come into your life just to teach you how to let go."

Large cinematic title at the bottom:
"Not Okay"
Small subtitle:
"But Pretending"

Use volumetric lighting, realistic shadows, shallow depth of field, soft bokeh, HDR, 85mm lens, f/1.4, cinematic color grading, ultra-detailed skin texture, 8K quality, realistic photo manipulation, professional Photoshop composite, highly emotional, dramatic atmosphere.

Negative Prompt: cartoon, anime, painting, illustration, CGI, 3D, low quality, blurry, oversaturated, extra people, duplicate face, deformed face, different hairstyle, different skin tone, unrealistic lighting, watermark, logo, text errors, bad anatomy, low resolution.`,
        title: "Dark Emotional Portrait",
      },
    ],
    photoBtnText: "Create Your Images",
    photoBtnLink: "https://chat.openai.com/",

    // Video Section (Optional - for this post, video part is not needed)
    videoStepTitle: "",
    videoStepImage: "",
    videoPrompt: "",
    videoBtnText: "",
    videoBtnLink: "",

    faqs: [
      {
        id: "em-faq-1",
        question: "Do I need any editing experience to create these photos?",
        answer:
          "No, you don't need any editing experience. All you need is a clear photo of yourself and the AI prompts provided in this tutorial. The AI tool does all the editing work for you.",
      },
      {
        id: "em-faq-2",
        question: "Which AI tool should I use?",
        answer:
          "You can use ChatGPT (with image generation), Bing Image Creator, or Midjourney. All of these tools work well with the prompts provided in this tutorial.",
      },
      {
        id: "em-faq-3",
        question: "Why is my result not looking like the example?",
        answer:
          "Make sure you are using a clear, high-quality photo of yourself. Also, make sure you copy the full prompt exactly as written. The more detailed your prompt, the better the result.",
      },
      {
        id: "em-faq-4",
        question: "Can I use these photos for commercial purposes?",
        answer:
          "Yes, but make sure to check the terms of service of the AI tool you are using. Some tools have restrictions on commercial use.",
      },
    ],
    conclusion: `Creating emotional AI photos is easier than most people think. You don't need professional editing skills or expensive software to make beautiful cinematic images. A clear photo, a detailed prompt, and a good AI tool are enough to get started. The most important thing is to describe your idea clearly so the AI understands the mood and story you want to create. Don't worry if your first result isn't perfect. Keep trying different prompts, change small details, and learn from each image you create. With a little practice, you will be able to create realistic emotional AI photos that look natural and catch people's attention. So, start experimenting today, be creative, and turn your simple photos into stunning emotional artwork that tells a powerful story.`,
    tags: [
      "Emotional AI Photo",
      "AI Portrait",
      "Cinematic Photo",
      "Heartbreak Photo",
      "AI Selfie",
      "ChatGPT Photo",
    ],
    isTrending: true,
    comments: [],
  },
  {
    id: "post-3",
    title: "Ultra Realistic Cinematic Mirror AI Photo Editing Prompt",
    categoryId: "cat-1", // Ai Photo Editing
    image: "/images/post3/mirror1.png",
    date: "July 13, 2026",
    author: "Vishu",
    introduction: `Mirror portrait photos are one of the biggest AI photo editing trends in 2026. If you use Instagram, Pinterest, or Facebook, you have probably seen people sharing stylish mirror photos with cinematic lighting, luxury backgrounds, and DSLR-quality details. These images look like they were captured by a professional photographer inside a premium studio, but in reality, many of them are created with AI in just a few minutes.

The best part is that you do not need expensive cameras, professional editing skills, or even a luxury location. With the help of modern AI image generators, you can turn a simple selfie into a stunning cinematic mirror portrait that looks incredibly realistic.

In this guide, you will learn everything you need to know about creating ultra-realistic cinematic mirror AI photos. From choosing the right photo to using the perfect prompt, every step is explained in simple English so anyone can follow it.`,

    whyTrending: `There are many reasons why this editing style has become viral in such a short time.

First, these images instantly grab attention because they look unique. Instead of taking a normal selfie, the mirror reflection creates a different perspective that feels more professional.

Another reason is the cinematic lighting. LED mirrors, soft shadows, and luxury backgrounds give every image a premium look without requiring any expensive equipment.

People also love this style because it works perfectly for Instagram posts, profile pictures, Reels thumbnails, and even wallpapers. Whether someone prefers a casual outfit or a luxury fashion look, the mirror portrait style suits almost everyone.

Most importantly, AI makes the entire process extremely easy. Anyone can create these professional-looking photos within a few minutes.`,

    creationIntro: `Some steps to create cinematic photos with AI will help you in creating these photos and by reading them you can easily create your own mirror selfie photo.

Download the Chatgpt app from Google Play Store and login with your Gmail account.
You need to come back to the website and copy the prompt given below the photo from this post.
Scroll down and click on the "Create Your Image" button.
You have to upload a nice photo of yourself by clicking on the plus icon of Chatgpt and send it by copying and pasting the prompt.
Chatgpt will now start taking your photo and in no time you will have a great mirror photo.
You have to download it by clicking on the arrow above.`,

    // 🔥 Multiple Images with Image → Prompt pattern
    photoStepTitle: "Steps to Generate Mirror Cinematic Photos:",
    photoItems: [
      {
        image: "/images/post3/mirror2.png",
        prompt: `"prompt":"Using the uploaded reference photo, create an ultra-realistic cinematic vertical portrait that preserves the person's facial features and hairstyle exactly as in the reference (no changes to face, haircut, or identity). The subject is wearing a crisp white tailored unbuttoned shirt and a thick polished silver chain. The camera is positioned behind the subject, who is standing in front of a modern LED-lit mirror in a dark, minimalist room. The image shows the back of the subject while the mirror provides a crystal-clear, sharp reflection of the face with a neutral, serious expression, making direct eye contact with the camera through the reflection. The subject is leaning slightly forward in an introspective pose. Soft cinematic lighting, subtle contrast, realistic skin texture, shallow depth of field, premium editorial look, vertical composition, ultra-detailed, photorealistic, 8K quality.`,
        title: "White Shirt Mirror Portrait",
      },
      {
        image: "/images/post3/mirror3.png",
        prompt: `Use the uploaded reference photo as the sole identity reference. Create an ultra-realistic cinematic vertical (9:16) mirror portrait of the same young man, preserving his face, facial features, hairstyle, hairline, skin tone, proportions, and identity exactly as in the reference photo (100% no changes). He has naturally voluminous, slightly messy dark hair and a defined jawline. He is wearing a tailored black unbuttoned shirt with a premium thick polished silver chain around his neck. The camera is positioned behind him, capturing the back of his head and shoulders while a modern LED-lit mirror provides a crystal-clear, perfectly sharp reflection of his face. In the reflection, he has a neutral, serious expression and makes direct eye contact with the camera lens. He leans slightly forward in an introspective pose. The setting is a dark, minimalist room illuminated by soft white LED mirror lighting with subtle cinematic rim lighting, realistic shadows, and gentle volumetric ambience. Ultra-photorealistic skin texture, natural fabric detail, premium editorial fashion photography, shallow depth of field, HDR, high contrast, realistic reflections, 85mm lens, f/1.8, professional color grading, 8K resolution, extremely detailed, cinematic, hyper-realistic. Do not alter the face, haircut, hairstyle, facial proportions, expression, or identity in any way`,
        title: "Black Shirt Mirror Portrait",
      },
    ],
    photoBtnText: "Create Your Images",
    photoBtnLink: "https://chat.openai.com/",

    // Video Section (Optional - not needed for this post)
    videoStepTitle: "",
    videoStepImage: "",
    videoPrompt: "",
    videoBtnText: "",
    videoBtnLink: "",

    faqs: [
      {
        id: "mirror-faq-1",
        question: "What is a Cinematic Mirror AI Photo?",
        answer:
          "A Cinematic Mirror AI Photo is a realistic portrait where the person is shown from behind while their face is clearly visible in a mirror. AI creates professional lighting, realistic reflections, and a luxury background to give the image a cinematic look.",
      },
      {
        id: "mirror-faq-2",
        question:
          "Do I need professional editing skills to create this type of photo?",
        answer:
          "No. You do not need any editing experience. Simply upload a clear photo, enter the AI prompt, and let the AI generate the final image.",
      },
      {
        id: "mirror-faq-3",
        question: "Which photo works best for this AI prompt?",
        answer:
          "A high-quality front-facing photo with good lighting gives the best results. Avoid blurry or low-resolution images because they can reduce the final image quality.",
      },
      {
        id: "mirror-faq-4",
        question:
          "Can I use these AI photos on Instagram and other social media?",
        answer:
          "Yes. These photos are perfect for Instagram posts, profile pictures, Reels covers, Facebook, WhatsApp, and other social media platforms.",
      },
      {
        id: "mirror-faq-5",
        question:
          "Why does the generated image sometimes look different from my original photo?",
        answer:
          "AI may slightly change facial details if the reference image is unclear or the prompt is not detailed enough. Using a high-quality photo and a well-written prompt helps keep your face more accurate.",
      },
      {
        id: "mirror-faq-6",
        question: "Can I change the outfit or background?",
        answer:
          "Yes. You can easily customize the prompt by changing the shirt color, background, lighting, accessories, or pose to create your own unique style.",
      },
      {
        id: "mirror-faq-7",
        question: "Is this AI prompt free to use?",
        answer:
          "Yes. You can use this prompt with any compatible AI image generator. However, some AI tools may require a premium subscription for higher-quality image generation.",
      },
    ],

    conclusion: `Creating an Ultra Realistic Cinematic Mirror AI Photo is now easier than ever. With the right reference photo, a detailed prompt, and a reliable AI image generator, you can create stunning mirror portraits that look like they were captured with a professional DSLR camera. This editing style has become one of the most popular AI photo trends because it combines luxury, realism, and cinematic lighting into a single image.

If you want the best results, always use a high-quality reference photo and avoid making unnecessary changes to your facial features in the prompt. A small improvement in the input can make a huge difference in the final output.

Copy the prompt shared in this guide, upload your photo, and create your own cinematic mirror portrait in just a few minutes. With a little creativity, you can generate eye-catching AI images that are perfect for Instagram, Facebook, WhatsApp, or your personal collection.`,

    tags: [
      "Cinematic Mirror Photo",
      "AI Mirror Portrait",
      "Ultra Realistic AI Photo",
      "Cinematic AI Selfie",
      "Luxury Mirror Photo",
      "AI Portrait Editing",
    ],
    isTrending: true,
    comments: [],
  },
  {
    id: "post-4",
    title: "Ultra Realistic Rooftop Blue Hour AI Photo Editing Prompt",
    categoryId: "cat-1", // AI Photo Editing
    image: "/images/post4/athestic1.png",
    date: "July 19, 2026",
    author: "Vishu",

    introduction: `Blue hour rooftop portraits have become one of the most popular AI photo editing trends in 2026. These images combine cinematic lighting, modern fashion, and an emotional urban atmosphere to create premium editorial-style portraits. Social media platforms like Instagram, Pinterest, and Facebook are filled with these aesthetic rooftop photos because they look like they were captured during a luxury fashion shoot.

The best part is that you do not need an expensive DSLR camera, professional lighting, or a rooftop photoshoot. With the help of modern AI image generators, you can transform a simple selfie into a stunning blue hour rooftop portrait within minutes.

In this guide, you will learn how to generate realistic rooftop editorial portraits using detailed AI prompts. Simply upload a clear reference photo, copy the prompt, and let AI create a cinematic masterpiece while preserving your facial features and identity.`,

    whyTrending: `This editing style has gone viral because it creates a luxury editorial look with very little effort.

The combination of blue hour lighting, rooftop scenery, blurred city lights, and cinematic color grading gives every portrait a premium feel that instantly grabs attention.

Another reason is the emotional storytelling. The relaxed pose, soft lighting, and urban skyline create a calm, nostalgic mood that looks perfect for Instagram posts, profile pictures, wallpapers, and fashion portfolios.

AI makes this style incredibly easy to create without requiring photography experience, expensive equipment, or professional editing software.`,

    creationIntro: `Follow these simple steps to create your own cinematic rooftop portrait.

Download the ChatGPT app from the Google Play Store and sign in with your Gmail account.
Come back to this website and copy the AI prompt provided below.
Click on the "Create Your Image" button.
Upload a clear front-facing photo of yourself by tapping the plus icon inside ChatGPT.
Paste the copied prompt and send it.
Within a few moments, ChatGPT will generate your premium rooftop cinematic portrait.
Finally, download the generated image using the download button.`,

    photoStepTitle: "Steps to Generate Rooftop Blue Hour Photos:",

    photoItems: [
      {
        image: "/images/post4/athestic2.png",
        title: "Blue Hour Rooftop Editorial Portrait",
        prompt: `Using the uploaded reference photo, create an ultra-realistic premium cinematic editorial portrait that preserves the person's facial features, hairstyle, face shape, skin tone, and identity exactly as in the reference (no changes to face or haircut). The subject is standing on a rooftop during blue hour, leaning naturally against a textured concrete wall with both hands inside the pockets of relaxed dark denim jeans. He is wearing a premium black open-collar shirt and stylish black rectangular sunglasses while looking slightly downward with a calm, confident expression. The background features a softly blurred modern city skyline with beautiful blue hour bokeh lights. Add a subtle motion-blurred passerby in the foreground to create cinematic storytelling and depth. Soft natural blue hour lighting, realistic shadows, editorial fashion photography, shallow depth of field, 85mm lens, f/1.8, HDR, ultra-realistic skin texture, luxury color grading, photorealistic, 8K quality.`,
      },

      {
        image: "/images/post4/athestic3.png",
        title: "Luxury Rooftop Fashion Portrait",
        prompt: `Use the uploaded reference photo as the only identity reference. Preserve the face, hairstyle, facial proportions, skin tone, and identity exactly as in the uploaded image without making any changes. Create an ultra-realistic cinematic rooftop fashion portrait during blue hour. The subject is leaning casually against a concrete pillar with hands inside loose dark jeans pockets while wearing a premium black unbuttoned shirt and elegant black sunglasses. The rooftop overlooks a modern metropolitan skyline filled with soft glowing bokeh lights. A motion-blurred pedestrian walks past in the foreground, creating an artistic editorial atmosphere. Cool blue and violet cinematic tones, natural soft lighting, shallow depth of field, realistic skin pores, fabric textures, subtle reflections on concrete, 85mm full-frame lens, f/1.8, HDR, photorealistic, premium editorial quality, ultra detailed, 8K resolution.`,
      },
      {
        image: "/images/post4/athestic4.png",
        title: "Luxury Rooftop Fashion Portrait",
        prompt: `A premium cinematic editorial portrait of a young man leaning against a concrete wall on a rooftop during blue hour. The atmosphere is calm, moody, and emotionally expressive with a subtle motion blur from a passing figure, creating a feeling of solitude, nostalgia, and quiet introspection.He has curly hair, wears black sunglasses, a black open-collar shirt, and dark loose jeans with hands in pockets, looking slightly downward in a relaxed, contemplative pose.The concrete wall has subtle textures and faint colorful reflections. The city skyline in the background is softly blurred with bokeh lights, enhancing depth and mood.Natural soft blue hour lighting with gentle shadows and a cinematic color grade in cool tones (blue, violet, gray).Shot with an 85mm lens, shallow depth of field, realistic skin texture, high detail, ultra-realistic, editorial fashion portrait quality.Aspect`,
      },
    ],

    photoBtnText: "Create Your Images",
    photoBtnLink: "https://chat.openai.com/",

    videoStepTitle: "",
    videoStepImage: "",
    videoPrompt: "",
    videoBtnText: "",
    videoBtnLink: "",

    faqs: [
      {
        id: "rooftop-faq-1",
        question: "What is a Blue Hour Rooftop AI Photo?",
        answer:
          "A Blue Hour Rooftop AI Photo is a cinematic editorial portrait created using AI where the subject is placed on a rooftop during blue hour with soft city lights, realistic lighting, and premium fashion styling.",
      },
      {
        id: "rooftop-faq-2",
        question: "Do I need photography experience?",
        answer:
          "No. Simply upload a clear reference photo, paste the AI prompt, and let the AI generate the final cinematic portrait.",
      },
      {
        id: "rooftop-faq-3",
        question: "Which reference photo gives the best results?",
        answer:
          "Use a high-resolution front-facing photo with good lighting. Clear facial details help AI preserve your identity more accurately.",
      },
      {
        id: "rooftop-faq-4",
        question: "Can I change the outfit or background?",
        answer:
          "Yes. You can easily edit the prompt to change clothing colors, sunglasses, lighting, city skyline, rooftop style, or overall mood.",
      },
      {
        id: "rooftop-faq-5",
        question: "Why does AI sometimes change my face?",
        answer:
          "If your uploaded image is blurry or poorly lit, AI may alter facial features slightly. Using a sharp reference image and a detailed prompt helps preserve your identity.",
      },
      {
        id: "rooftop-faq-6",
        question: "Can I post these images on Instagram?",
        answer:
          "Yes. These rooftop editorial portraits are perfect for Instagram posts, profile pictures, Reels covers, Pinterest, Facebook, and WhatsApp.",
      },
      {
        id: "rooftop-faq-7",
        question: "Is this AI prompt free to use?",
        answer:
          "Yes. You can use this prompt with compatible AI image generators. Some platforms may require a premium subscription for the highest image quality.",
      },
    ],

    conclusion: `Creating an Ultra Realistic Rooftop Blue Hour AI Portrait has never been easier. With a high-quality reference photo and a detailed AI prompt, you can generate stunning editorial-style portraits that look like they were captured during a professional fashion photoshoot.

The cinematic rooftop environment, soft blue hour lighting, luxury fashion styling, and blurred city lights combine to create an elegant and timeless aesthetic. These portraits are perfect for social media, profile pictures, wallpapers, and personal portfolios.

Simply copy the prompt provided in this guide, upload your reference photo, and let AI transform it into a premium rooftop editorial masterpiece in just a few minutes.`,

    tags: [
      "Blue Hour AI Photo",
      "Rooftop Portrait",
      "Editorial AI Photo",
      "Cinematic AI Portrait",
      "Luxury Rooftop Photo",
      "AI Fashion Portrait",
      "Blue Hour Photography",
      "AI Photo Editing",
    ],

    isTrending: true,
    comments: [],
  },
];
